version: "3"

services:
  postgres:
    image: postgres
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "wookiepedia", "-U", "postgres" ]
      interval: 3s
      retries: 5
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: wookiepedia
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgres

  helper:
    image: helper
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://postgres:password@postgres:5432/wookiepedia
    volumes:
      - ./:/app

  app:
    image: ${APP_NAME}:${VERSION}
    environment:
      DATABASE_URL: postgres://postgres:password@postgres:5432/wookiepedia
      APP_PORT: 8080
      APP_HOST: 0.0.0.0
      APP_DATABASE_URL: postgres://postgres:password@postgres/wookiepedia
    ports:
      - 8080:8080
volumes:
  postgres: